name: Lua Code Quality

on:
  pull_request:
  workflow_dispatch:

jobs:
  Code_Linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v13.0.0
        with:
          luaVersion: '5.1'

      - name: Set up Luarocks
        uses: leafo/gh-actions-luarocks@v6.1.0

      - name: Install Luacheck
        run: luarocks install luacheck

      - name: Run Luacheck
        run: luacheck ./


