name: Lua Code Quality

on:
  pull_request:
  workflow_dispatch:

jobs:
  Code_Linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v11.0.0
        with:
          luaVersion: '5.1'

      - name: Set up Luarocks
        uses: leafo/gh-actions-luarocks@v4.3.0

      - name: Install Luacheck
        run:  |
          sudo apt-get install luarocks
          sudo luarocks install luacheck

      - name: Run Luacheck APR-Core
        run: luacheck ./APR-Core

      - name: Run Luacheck Routes
        run: luacheck ./Routes


