name: Discord Release Notification

on:
  release:
    types: [published]  # Triggers on newly published releases

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests python-dotenv

      - name: Post release notes to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python .github/scripts/post_discord.py --tag "${{ github.event.release.tag_name }}" --body "${{ github.event.release.body }}"
