name: Release Addon

on:
  push:
    tags:
      - '**'

env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: WoW Packager
        uses: BigWigsMods/packager@master
        with:
          args: -p 618667 -w 26457 -a XKq9xXKy

