name: Release Addon

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      target_type:
        description: 'Branch/Tag to release'
        required: true
        default: 'branch'
        type: choice
        options:
          - branch
          - tag
      target_name:
        description: 'Branch or tag name'
        required: true
        default: 'main'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.target_type == 'tag' && format('refs/tags/{0}', github.event.inputs.target_name) || format('refs/heads/{0}', github.event.inputs.target_name)) || github.ref }}

      - name: WoW Packager
        uses: BigWigsMods/packager@v2.6.1
        with:
          args: -p 965240 -a rN4VYvKD -w 26704

